version: '3'

services:
  redis-server:
    image: "redis:alpine3.19"
    ports:
      - '6379:6379'
  
  miniature:
    build: .
    environment:
      - RedisConnString=redis-server:6379
      - BasePath=localhost:8080
      - Scheme=http
    ports:
      - "8080:8080"
    depends_on:
      - redis-server


